### ISSUE TITLE
Checking productions status

### ISSUE THREAD

**Issue by lancoer** [FutureSPL/future-takeover-program#3]
Hi @L0STE 
Seems your too busy building stuffs, but...
Is Vercel deployment working fine atm? [migrator-sable.vercel.app](https://migrator-sable.vercel.app/)
Also this TG link: https://t.me/future_dao doesn't generate any group invite link...

**Comment by L0STE** [comment]
Good morning, not sure what's the current status of the Vercel Deployment since we've not been working on this for the past 3+ months...

**Comment by lancoer** [comment]
Really? You mean this is quite abandoned and your not currently working on a project?

**Comment by L0STE** [comment]
I'm working on a project, I'm not currently working for Future so I don't know what's the current status of the page. 

Not sure where all this is coming from (?)

**Comment by lancoer** [comment]
Got it thanks!
